kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: infrastructure
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /C/PJMICROSTORE/ELASTICSEARCH
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: infrastructure
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
 