apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontstore
  namespace: external
  labels:
    app: frontstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontstore
  template:
    metadata:
      labels:
        app: frontstore
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://localhost:9090
        - name: APP_URL
          value: http://localhost:8080
        - name: AUTH_URL
          value: http://localhost:5000
        image: mwpro/pjmicrostore-front-store
        name: frontstore
        ports:
        - containerPort: 80