apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipping
  namespace: checkout
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - env:
        - name: Identity__Authority
          value: http://identityapi.identity
        image: mwpro/pjmicrostore-checkout-shipping:1.0.1
        name: shipping
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1