version: '3.7'
services:
  elasticsearch:
    networks:
      - pjmicrostore
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    ports: 
      - "9200:9200"
  kibana:
    networks:
      - pjmicrostore
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: kibana
    ports: 
      - "5601:5601"
    depends_on: ['elasticsearch']
  rabbitmq:
    networks:
      - pjmicrostore
    image: rabbitmq:3
    container_name: rabbitmq
    volumes: 
      - "./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins"
    ports: 
      - "15672:15672"
      - "5672:5672"
  sqlserver:
    networks:
      - pjmicrostore
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sqlDevPassw0rd
    ports:
      - "1433:1433"
  azurestorage:
    networks:
      - pjmicrostore
    image: arafato/azurite
    container_name: azurestorage
    ports:
      - "10000:10000"
    environment: 
      - executable=blob
    volumes:
      - "./local-azurestorage:/opt/azurite/folder"

networks:
  pjmicrostore:
    name: pjmicrostore