version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    ports: 
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: kibana
    ports: 
      - "5601:5601"
    depends_on: ['elasticsearch']
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "15672:15672"
      - "5672:5672"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sqlDevPassw0rd
    ports:
      - "1433:1433"