kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: infrastructure
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
 